[[tmux]]
arch = "aarch64"
git-tree-sha1 = "5696cb75848beba8ae05e202e23959a202258b1d"
os = "macos"

    [[tmux.download]]
    sha256 = "7cca744caa5bfa82087eaec0b4487817d2805e2101ac6b5a0da4ad58c2449b76"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.3.0+0/tmux.v3.3.0.aarch64-apple-darwin.tar.gz"
[[tmux]]
arch = "aarch64"
git-tree-sha1 = "e647756c77520cc56aae7588eb377a90be0e4456"
libc = "glibc"
os = "linux"

    [[tmux.download]]
    sha256 = "437382c8a905bcc0a274c0afaacbce8dace822196615858f491189d5eeb8e25c"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.3.0+0/tmux.v3.3.0.aarch64-linux-gnu.tar.gz"
[[tmux]]
arch = "aarch64"
git-tree-sha1 = "b862720fff7b7e47b98b331a32318bdce4e91a69"
libc = "musl"
os = "linux"

    [[tmux.download]]
    sha256 = "683da0447e460be98fe451c5d064c87b7c4f62004c64d9632464cea6d79bd7c3"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.3.0+0/tmux.v3.3.0.aarch64-linux-musl.tar.gz"
[[tmux]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f26722d4de178396b001d7b6347d8400d5022316"
libc = "glibc"
os = "linux"

    [[tmux.download]]
    sha256 = "22a340fdd32306b0e171d6079b8936dddead24a86f6590a81cfd7229f019e0f8"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.3.0+0/tmux.v3.3.0.armv6l-linux-gnueabihf.tar.gz"
[[tmux]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c93b4e80f7bf5a68fe2572143fd618a9742ddf7b"
libc = "musl"
os = "linux"

    [[tmux.download]]
    sha256 = "377eb36ed9ccc2aba7ea969ef16b348935c0c5899627338f28aaa265f2add5ab"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.3.0+0/tmux.v3.3.0.armv6l-linux-musleabihf.tar.gz"
[[tmux]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "080698304a07e6672313b3b0b83e2a818be1ba2d"
libc = "glibc"
os = "linux"

    [[tmux.download]]
    sha256 = "f07b9b2f502640fe22267434d184a9174dba656f3b841ba3ba2fb6c3c7874b21"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.3.0+0/tmux.v3.3.0.armv7l-linux-gnueabihf.tar.gz"
[[tmux]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c637f16b46d67d77f26ca892a2d24556ca13ea31"
libc = "musl"
os = "linux"

    [[tmux.download]]
    sha256 = "fdb0a3fe38253691162ede987c4bf27fc6c31656fcd98b66d8c58865a62edf74"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.3.0+0/tmux.v3.3.0.armv7l-linux-musleabihf.tar.gz"
[[tmux]]
arch = "i686"
git-tree-sha1 = "4ea448a5e52327e4306c33cd48a44f935187cd2c"
libc = "glibc"
os = "linux"

    [[tmux.download]]
    sha256 = "9fc98b273dc0b5d0a816dec561ffeb65c91eae1cf9240b3642fb15e672a72750"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.3.0+0/tmux.v3.3.0.i686-linux-gnu.tar.gz"
[[tmux]]
arch = "i686"
git-tree-sha1 = "ad5ab30984c59baa66b68088020b9861829c5791"
libc = "musl"
os = "linux"

    [[tmux.download]]
    sha256 = "363b42388702272fb85fe0bd9e63a5d054938281449d317e9b5da2add688ef74"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.3.0+0/tmux.v3.3.0.i686-linux-musl.tar.gz"
[[tmux]]
arch = "powerpc64le"
git-tree-sha1 = "3db7c7f859b6861e46172ae76326a0e2e2cbf9ff"
libc = "glibc"
os = "linux"

    [[tmux.download]]
    sha256 = "bf5878e242ebb9a92cd3b4f058cbdd05c77189ecd6cdf6e49738bc5d0946819a"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.3.0+0/tmux.v3.3.0.powerpc64le-linux-gnu.tar.gz"
[[tmux]]
arch = "x86_64"
git-tree-sha1 = "94e391f4fd931d351d3bd7d2b448a432195dff30"
os = "macos"

    [[tmux.download]]
    sha256 = "f9f0a733ec09dc27d5b8a303553313db1fa42b2cddae6c456262639d91b72f6f"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.3.0+0/tmux.v3.3.0.x86_64-apple-darwin.tar.gz"
[[tmux]]
arch = "x86_64"
git-tree-sha1 = "0c72e8a23bb796b59293011e6220e59c4b3de60e"
libc = "glibc"
os = "linux"

    [[tmux.download]]
    sha256 = "cb6c79b9f68a0a1b2ceeafb6b2f728b09c77203896f69689d6c3024922177b74"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.3.0+0/tmux.v3.3.0.x86_64-linux-gnu.tar.gz"
[[tmux]]
arch = "x86_64"
git-tree-sha1 = "da827906364fe7c2f82a53cf7da1e3a1acf33496"
libc = "musl"
os = "linux"

    [[tmux.download]]
    sha256 = "88dcf4e6d989b8db456b7c445610a3264086448668db152b9bee71441370890d"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.3.0+0/tmux.v3.3.0.x86_64-linux-musl.tar.gz"
[[tmux]]
arch = "x86_64"
git-tree-sha1 = "784bc6f840e512eb27707e834bf34e5865e79861"
os = "freebsd"

    [[tmux.download]]
    sha256 = "a2e3a488f16f3a4f87e00a156b984d27d490a8709afc08780565e01e331013a7"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.3.0+0/tmux.v3.3.0.x86_64-unknown-freebsd.tar.gz"
