[[tmux]]
arch = "aarch64"
git-tree-sha1 = "df0322c85801313fa060329942e26bd867c076e1"
os = "macos"

    [[tmux.download]]
    sha256 = "1e8cf7f2c73fc8d5d9feedfe090c856ed4e0114b109fc08743fb721b037d457d"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.7.3+0/tmux.v3.7.3.aarch64-apple-darwin.tar.gz"
[[tmux]]
arch = "aarch64"
git-tree-sha1 = "309e90380d5a6783ca4511cb334e8a545b384a8f"
libc = "glibc"
os = "linux"

    [[tmux.download]]
    sha256 = "3e2c5bf281ae651b31419c67f07c88ef5180ab4d4817102c7c8121fda2c1e11b"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.7.3+0/tmux.v3.7.3.aarch64-linux-gnu.tar.gz"
[[tmux]]
arch = "aarch64"
git-tree-sha1 = "d568298f706ea9b8405ae1547ef6d87889fdb469"
libc = "musl"
os = "linux"

    [[tmux.download]]
    sha256 = "573cc381fe86e9a7b9c5e7591bba4f3adbdf3ab619da964dd2563ea5effdbb39"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.7.3+0/tmux.v3.7.3.aarch64-linux-musl.tar.gz"
[[tmux]]
arch = "aarch64"
git-tree-sha1 = "4da7c49563de93bffbb4a8e51e48d80be4b3d9b1"
os = "freebsd"

    [[tmux.download]]
    sha256 = "23e5817c96d190a0dabc21952feb8d022884420922b344ff434d157e411b5528"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.7.3+0/tmux.v3.7.3.aarch64-unknown-freebsd.tar.gz"
[[tmux]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "75e4ad350e9b685c7d3af605fd93b386e8e30e03"
libc = "glibc"
os = "linux"

    [[tmux.download]]
    sha256 = "480e49454e08c3c676421db351c75d8250644829549617c72349998eba94649b"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.7.3+0/tmux.v3.7.3.armv6l-linux-gnueabihf.tar.gz"
[[tmux]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6d6535a57f9680cf73a583b771e18254ab6f72d3"
libc = "musl"
os = "linux"

    [[tmux.download]]
    sha256 = "409b158be8c0ea85db0a6f00ca13cd272fe791bbac79745af061b60c801ab0eb"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.7.3+0/tmux.v3.7.3.armv6l-linux-musleabihf.tar.gz"
[[tmux]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b51e79e019a8da90d21b9371527a846c684d7d46"
libc = "glibc"
os = "linux"

    [[tmux.download]]
    sha256 = "17eeb8a531d489eb6e4763e9a80c7c6e0b7f920704abc11f0e2cb6f1662eb6b2"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.7.3+0/tmux.v3.7.3.armv7l-linux-gnueabihf.tar.gz"
[[tmux]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3d7c372fe4ed11c58c470989bb87386865d65e43"
libc = "musl"
os = "linux"

    [[tmux.download]]
    sha256 = "947d4e1c5fa48b4d0e032c633fbee43df82ea1cdea5301ba74a591fc824d1823"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.7.3+0/tmux.v3.7.3.armv7l-linux-musleabihf.tar.gz"
[[tmux]]
arch = "i686"
git-tree-sha1 = "e0fa0edeea9b7634c118257dd47f46fc4bb27fd8"
libc = "glibc"
os = "linux"

    [[tmux.download]]
    sha256 = "dfaedb003535bc5ae39d4bde44217d7a216186906ec97dd2fb53a7ea66e8ffd4"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.7.3+0/tmux.v3.7.3.i686-linux-gnu.tar.gz"
[[tmux]]
arch = "i686"
git-tree-sha1 = "c966536c8fb3e09062d1ff64286cb568fc2c4f94"
libc = "musl"
os = "linux"

    [[tmux.download]]
    sha256 = "da19577dfcab2378abefd34bd01d49efc782c6307fafd54eee670b1b7b85ad9e"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.7.3+0/tmux.v3.7.3.i686-linux-musl.tar.gz"
[[tmux]]
arch = "powerpc64le"
git-tree-sha1 = "54e582087da3243a2bf8e1f96ed5a43a3c44ef65"
libc = "glibc"
os = "linux"

    [[tmux.download]]
    sha256 = "d39e41d4bf6e31e65a1b3f383bbc8e590f727558738b8d0c23a8e9515fb20dfe"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.7.3+0/tmux.v3.7.3.powerpc64le-linux-gnu.tar.gz"
[[tmux]]
arch = "riscv64"
git-tree-sha1 = "bc85f57f571f9699534a2d7588f5d776dc259cad"
libc = "glibc"
os = "linux"

    [[tmux.download]]
    sha256 = "3188a95debe7e3ff0b6e65d1dd1361c887b1a1d44fba72c15d40f52de0b0858a"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.7.3+0/tmux.v3.7.3.riscv64-linux-gnu.tar.gz"
[[tmux]]
arch = "x86_64"
git-tree-sha1 = "5279166bb0a0ddf9437d828b9ff2936eade6c549"
os = "macos"

    [[tmux.download]]
    sha256 = "339dc8a3f9cbb1218867e6c214f725e7ff18628966c8b754ebb6658473755a3b"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.7.3+0/tmux.v3.7.3.x86_64-apple-darwin.tar.gz"
[[tmux]]
arch = "x86_64"
git-tree-sha1 = "0d06b24e48ceff7a070523530eed055649bbbe72"
libc = "glibc"
os = "linux"

    [[tmux.download]]
    sha256 = "0a13d55046a4065639e4beca41989e046df062021da5753df1c993332c43dbf7"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.7.3+0/tmux.v3.7.3.x86_64-linux-gnu.tar.gz"
[[tmux]]
arch = "x86_64"
git-tree-sha1 = "c48d0c9e28e0348a68b0fee877bfe33428e48bb5"
libc = "musl"
os = "linux"

    [[tmux.download]]
    sha256 = "63463b7e6a7aad1a759eaa4d7ccbe7ffe74b7f3e2347f2df01e89f5f31d8a54f"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.7.3+0/tmux.v3.7.3.x86_64-linux-musl.tar.gz"
[[tmux]]
arch = "x86_64"
git-tree-sha1 = "c50abfcf1a92f42b932ca51745391e5522fdbce4"
os = "freebsd"

    [[tmux.download]]
    sha256 = "99b46cf00dd553afce80acd03859847242c83db62fa0745595c85a91a092f5ce"
    url = "https://github.com/JuliaBinaryWrappers/tmux_jll.jl/releases/download/tmux-v3.7.3+0/tmux.v3.7.3.x86_64-unknown-freebsd.tar.gz"
